### ISSUE TITLE
Account access

### ISSUE THREAD

**Issue by Martii** [devcnn88/MHAutoBotEnhanced#2]
> This is alternate account of ... because i cannot log in using that account anymore.

Would you elaborate more on this please... can't log into google account or can't log into OUJS account?... or what?

TIA,
OUJS Admin

**Comment by devcnn88** [comment]
Hi Martii,

If i recall correctly, initially i register an OUJS account as devcnn88gmail. But somehow I am unable to login to this account afterward. I dont know exactly what's happening. So I just create another account with username devcnn. I can log into google account but not the devcnn88gmail OUJS account.

**Comment by Martii** [comment]
Have you retried since May 2015 of this year? We did have some google changes... if you can, and validate on OUJS that you are moving over to your newest account I can transfer your stats there... but only if you can get into it with that email address and let me know there.

**Comment by devcnn88** [comment]
I didnt retried since I can successfully log into my new account i.e. devcnn. How do I validate on OUJS if I intend to transfer my stats? And what if I dont mind about the old account stat by just removing that account from OUJS?

**Comment by Martii** [comment]
Using your old gmail address login with that _(on google first)_... then try to login on OUJS using the OUJS user name... it may let you in it may not. The auth keys I have for both your accounts are different so I know at least it's two different gmail accounts that you did... they are close enough on "Member since" date that it's probably you but I really need the additional confirmation. The reason why I'm buggin' ya is because that script will eventually show up in our moderation and it may end being killed e.g. perma banned and that gmail account won't be able to ever login... so I'm nipping it in the bud per say before that happens... or at least trying.

**Comment by devcnn88** [comment]
Ok. I have tried to login with various combination of username:
1. devcnn - successful login as user "devcnn" through github
2. devcnn88gmail - failed to login
3. devcnn88gmail.com - successful login as user "devcnn" through gmail i.e. devcnn88@gmail.com

I dont know if I did it correctly but I only can log into my newest account, user "devcnn".
So what now? Anything else I can do? It's been a long time and I have forgot about the username/login method for old OUJS account.

**Comment by Martii** [comment]
Well that's peculiar... the OUJS devcnn88gmail.com account I know from our prepping is your devcnn88@gmail.com address so it's a little odd that it would not direct you to the OUJS equivalent account.

Hmm... well there may be nothing I can do about it... since the auth keys are different it could have been a google hiccup but without having some reference on that old account _(usually I look for those in the Profile)_ it is probably going to sit around accumulating bad votes and eventually show up in moderation. Hmmm... Well I appreciate you trying. :) I'll see if I can find any other method around that time that would corrupt your auth key on OUJS but I don't recall any issues at that time with google logging in.

So one last question... both OUJS accounts were/are using the same gmail account?

Sidenote: `devcnn88gmail` [doesn't currently exist on OUJS](https://openuserjs.org/users?q=devcnn) so you wouldn't be able to get in with that.

**Comment by Martii** [comment]
Hmmm looks like google's access to OUJS is stored at https://security.google.com/settings/security/permissions ... at least on my account.

**Comment by devcnn88** [comment]
Yes. Both of the accounts use the same google account. I checked on the link you provided and OUJS do appeared in the list and provide access to google account too. Even google account is perma banned, there is still login via github method. By the way, thanks on your help and effort. I appreciate it.

**Comment by Martii** [comment]
Okay... well it sounds like you missed the google migration period... what I can do for your `devcnn88` account is remove that google auth and let you readd it... and I've mostly convinced myself that the dead account is yours so I'll go ahead and transfer the stats and manually delete `devcnn88gmail.com` account... if for some reason this is a mistake the auth key can be reused on OUJS. e.g. resign up and reauthorize.... give me a few to make this change.

**Comment by Martii** [comment]
Alright... stats transferred from `devcnn88gmail.com` and that OUJS account deleted manually... and your `devcnn88` OUJS account is google free... if you want to readd it go to https://openuserjs.org/user/preferences and Add another form of authentication. You should be reprompted for access to your Google profile _(say yes otherwise it won't work)_. Please let me know how it goes. Thanks.

**Comment by devcnn88** [comment]
Yes it works. I can add another form of authentication and successfully login through google and github too. Thousand thanks on your help! :-)

**Comment by Martii** [comment]
Just let us know on OUJS development _(here on GH)_ if you have any issues like this... I'd be more than happy to see what I can do. Thank you. :)
